### ISSUE TITLE
Point Cloud input data

### ISSUE THREAD

**Issue by sabienAmb** [Scrawk/Marching-Cubes#1]
I would like to add an option for allowing the user to use an array of Vector3's as the input, instead of the fractal noise. How would you recommend going about this?

**Comment by Scrawk** [comment]
Marching cubes only works on a array of voxel values not geometry like a point cloud.
You would have to convert your points to a signed distance field to use as the voxels. Do not know a method of hand but googling “point cloud to signed distance field” should bring something up.

**Comment by sabienAmb** [comment]
What does the float value in a voxel represent?

**Comment by Scrawk** [comment]
It represents a isosurface. Normally the surface is at 0 but it can be changed to any value. If a cell has a value of -1 and its neighbor a value of 1 then the mesh surface would be at their mid point.
