### ISSUE TITLE
Added Color. 

### ISSUE THREAD

**Issue by xsmarty** [Scrawk/Marching-Cubes#2]
Hi there, 
thanks for the great work, it was very useful. 

Please find enclosed an enhanced version working with colour. 
Vertex color info is propagated to edges during marching. 

[MarchingCubes.zip](https://github.com/Scrawk/Marching-Cubes/files/1656492/MarchingCubes.zip)

![screenshot 2018-01-23 16 19 24](https://user-images.githubusercontent.com/13020919/35283798-769d22ae-0059-11e8-939e-24f0ac457e71.png)

Many thanks, 
Xavier.

**Comment by sabienAmb** [comment]
What data are you using as input? This doesn't look like the noise he used originally

**Comment by xsmarty** [comment]
I am building the isosurface from a colored octomap. 

If you want to use the original example, or get an idea of how it works : 
[MarchingColorCubeExample.zip](https://github.com/Scrawk/Marching-Cubes/files/1659394/MarchingColorCubeExample.zip)

The result : 
![screenshot 2018-01-24 11 13 28](https://user-images.githubusercontent.com/13020919/35326690-b4d7cdfa-00f7-11e8-92a3-4f7f25d70d27.png)
