### ISSUE TITLE
List of indices is never used?

### ISSUE THREAD

**Issue by ghost** [Scrawk/Marching-Cubes#4]
Hello, i've been messing around with your project for a while, and i've noticed that the IList passed as parameter to the March() method is populated but never used in your code example. Is this intended?

Here you rebuild all the indexes manually.

`for (int i = 0; i < numMeshes; i++)
            {

                List<Vector3> splitVerts = new List<Vector3>();
                List<int> splitIndices = new List<int>();

                for (int j = 0; j < maxVertsPerMesh; j++)
                {
                    int idx = i * maxVertsPerMesh + j;

                    if (idx < verts.Count)
                    {
                        splitVerts.Add(verts[idx]);
                        splitIndices.Add(j);
                    }
                }`

**Comment by Scrawk** [comment]
Its not used in the example but if you know the mesh is always going to have less than 65000 verts then you dont need to split the mesh and you can use that list for the indices.
